name: LyaimTech backend

on: 
    push: 
        branches:  [ main ]
        paths: 
          - 'backend/**' 

jobs: 
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            
            - name: Docker Login
              uses: docker/login-action@v2
              with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_PASSWORD}}
            
            - name: Build and push
              uses: docker/build-push-action@v5 
              with:
                context: ./backend
                file: ./backend/Dockerfile
                push: true
                tags: narsibhati6545/lyaim-tech-backend:${{github.sha}} 
                 

