name: LyaimTech backend

on: 
    push: 
        branches: [ main ]

jobs: 
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            
            - name: Docker Login
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Build and push
              uses: docker/build-push-action@v5 
              with:
                context: ./backend
                file: ./backend/Dockerfile
                push: true
                tags: |
                  narsibhati6545/lyaim-tech-backend:${{ github.sha }} 
                  narsibhati6545/lyaim-tech-backend:latest
            
            - name: Deploy to VM
              uses: appleboy/ssh-action@v1.2.0
              with:
                host: "98.81.206.98" # Your VM IP
                username: "ubuntu" # Your SSH user
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: 22
                script: whoami

                  # docker pull narsibhati6545/lyaim-tech-backend:latest
                  # docker stop lyaim-backend || true
                  # docker rm lyaim-backend || true
                  # docker run -d --name lyaim-backend -p 9000:9000 --restart always narsibhati6545/lyaim-tech-backend:latest