name: LyaimTech backend

on: 
    push: 
        branches:  [ main ]
        paths: 
          - 'backend/**' 
          - '.github/workflows/cd_backend.yaml'

jobs: 
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            
            - name: Docker Login
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Build and push
              uses: docker/build-push-action@v5 
              with:
                context: ./backend
                file: ./backend/Dockerfile
                push: true
                tags: |
                  narsibhati6545/lyaim-tech-backend:${{github.sha}} 
                  narsibhati6545/lyaim-tech-backend:latest
            
            - name: Deploy to VM
              run: |
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
                  chmod 600 ~/ssh_key
                  ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@18.206.107.28 -t "
                    docker pull narsibhati6545/lyaim-tech-backend:latest &&
                    docker stop lyaim-backend || true &&
                    docker rm lyaim-backend || true &&
                    docker run -d --name lyaim-backend -p 9000:9000 narsibhati6545/lyaim-tech-backend:latest"



                 

