name: LyaimTech frontend

on: 
    push: 
        branches:  [ main ]
        paths: 
            - 'frontend/**'

jobs: 
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            
            - name: Docker Login
              uses: docker/login-action@v2
              with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_PASSWORD}}
            
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: ./frontend
                file: ./frontend/Dockerfile
                push: true
                tags: narsibhati6545/lyaim-tech-frontend:${{github.sha}} 
                 

