name: LyaimTech frontend

on: 
    push: 
        branches: [ main ]

jobs: 
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3

            - name: Docker Login
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: ./frontend
                file: ./frontend/Dockerfile
                push: true
                tags: | 
                  narsibhati6545/lyaim-tech-frontend:${{ github.sha }} 
                  narsibhati6545/lyaim-tech-frontend:latest

            - name: Deploy to VM
              uses: appleboy/ssh-action@v0.1.10
              with:
                host: "18.206.107.28" # Your VM IP
                username: "ubuntu" # Your SSH user
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                  docker pull narsibhati6545/lyaim-tech-frontend:latest
                  docker stop lyaim-frontend || true
                  docker rm lyaim-frontend || true
                  docker run -d --name lyaim-frontend -p 3000:3000 --restart always narsibhati6545/lyaim-tech-frontend:latest